letra = []
c = int(input())
A, B, C, D, E = str(input()).split()
A = int(A)
B = int(B)
C = int(C)
D = int(D)
E = int(E)
letra.append(A)
letra.append(B)
letra.append(C)
letra.append(D)
letra.append(E)
print(letra.count(c))